#!/bin/bash

# call with ./02 <username>

REQ_NUM_ARGS=2
num_args=$#



if [ num_args -lt REQ_NUM_ARGS ];
then
	echo "Not enough arguments"
	exit 1
fi



if [ "$EUID" -ne 0 ]
then
	echo "Must run as root"
fi


