#!/bin/bash

# call with ./02 <username>

USER_LOG=$(getent passwd | cut -d: -f1)

check_user()
{
	for u in $USER_LOG
	do
		if [ "u" == "$1" ]
			return 0
		fi
	done
	return 1
}

if [ $# -ne 1 ];
then
	echo "Usage: ./${0} <username>"
	exit
else
	USER=$1
	check_user $1
	ret=$?

fi

if [ $ret -eq 0 ]
then
	if [ "$EUID" -ne 0 ]
	then
		echo "Must run as root"
		exit
	else
		killall -KILL -u $USER > /dev/null 2>&1
		pkill -KILL $USER > /dev/null 2>&1
		userdel -u $USER > /dev/null 2>&1
		rm -rf /home/$USER > /dev/null 2>&1
		echo "$USER has been deleted"
		exit
	fi
else
	echo "$USER is not logged"
fi	
